// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aqcommon.proxies;

public class QueryVariable
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject queryVariableMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AqCommon.QueryVariable";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		VariableName("VariableName"),
		VariableType("VariableType"),
		AssociatedObjectValue("AssociatedObjectValue"),
		BooleanValue("BooleanValue"),
		DateTimeValue("DateTimeValue"),
		DecimalValue("DecimalValue"),
		IntegerValue("IntegerValue"),
		LongValue("LongValue"),
		StringValue("StringValue");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public QueryVariable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected QueryVariable(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject queryVariableMendixObject)
	{
		if (queryVariableMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, queryVariableMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.queryVariableMendixObject = queryVariableMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'QueryVariable.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static aqcommon.proxies.QueryVariable initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return aqcommon.proxies.QueryVariable.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aqcommon.proxies.QueryVariable initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aqcommon.proxies.QueryVariable(context, mendixObject);
	}

	public static aqcommon.proxies.QueryVariable load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aqcommon.proxies.QueryVariable.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of VariableName
	 */
	public final java.lang.String getVariableName()
	{
		return getVariableName(getContext());
	}

	/**
	 * @param context
	 * @return value of VariableName
	 */
	public final java.lang.String getVariableName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VariableName.toString());
	}

	/**
	 * Set value of VariableName
	 * @param variablename
	 */
	public final void setVariableName(java.lang.String variablename)
	{
		setVariableName(getContext(), variablename);
	}

	/**
	 * Set value of VariableName
	 * @param context
	 * @param variablename
	 */
	public final void setVariableName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String variablename)
	{
		getMendixObject().setValue(context, MemberNames.VariableName.toString(), variablename);
	}

	/**
	 * Set value of VariableType
	 * @param variabletype
	 */
	public final aqcommon.proxies.QueryVariableType getVariableType()
	{
		return getVariableType(getContext());
	}

	/**
	 * @param context
	 * @return value of VariableType
	 */
	public final aqcommon.proxies.QueryVariableType getVariableType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.VariableType.toString());
		if (obj == null) {
			return null;
		}
		return aqcommon.proxies.QueryVariableType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of VariableType
	 * @param variabletype
	 */
	public final void setVariableType(aqcommon.proxies.QueryVariableType variabletype)
	{
		setVariableType(getContext(), variabletype);
	}

	/**
	 * Set value of VariableType
	 * @param context
	 * @param variabletype
	 */
	public final void setVariableType(com.mendix.systemwideinterfaces.core.IContext context, aqcommon.proxies.QueryVariableType variabletype)
	{
		if (variabletype != null) {
			getMendixObject().setValue(context, MemberNames.VariableType.toString(), variabletype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.VariableType.toString(), null);
		}
	}

	/**
	 * @return value of AssociatedObjectValue
	 */
	public final java.lang.String getAssociatedObjectValue()
	{
		return getAssociatedObjectValue(getContext());
	}

	/**
	 * @param context
	 * @return value of AssociatedObjectValue
	 */
	public final java.lang.String getAssociatedObjectValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssociatedObjectValue.toString());
	}

	/**
	 * Set value of AssociatedObjectValue
	 * @param associatedobjectvalue
	 */
	public final void setAssociatedObjectValue(java.lang.String associatedobjectvalue)
	{
		setAssociatedObjectValue(getContext(), associatedobjectvalue);
	}

	/**
	 * Set value of AssociatedObjectValue
	 * @param context
	 * @param associatedobjectvalue
	 */
	public final void setAssociatedObjectValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String associatedobjectvalue)
	{
		getMendixObject().setValue(context, MemberNames.AssociatedObjectValue.toString(), associatedobjectvalue);
	}

	/**
	 * @return value of BooleanValue
	 */
	public final java.lang.Boolean getBooleanValue()
	{
		return getBooleanValue(getContext());
	}

	/**
	 * @param context
	 * @return value of BooleanValue
	 */
	public final java.lang.Boolean getBooleanValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BooleanValue.toString());
	}

	/**
	 * Set value of BooleanValue
	 * @param booleanvalue
	 */
	public final void setBooleanValue(java.lang.Boolean booleanvalue)
	{
		setBooleanValue(getContext(), booleanvalue);
	}

	/**
	 * Set value of BooleanValue
	 * @param context
	 * @param booleanvalue
	 */
	public final void setBooleanValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean booleanvalue)
	{
		getMendixObject().setValue(context, MemberNames.BooleanValue.toString(), booleanvalue);
	}

	/**
	 * @return value of DateTimeValue
	 */
	public final java.util.Date getDateTimeValue()
	{
		return getDateTimeValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTimeValue
	 */
	public final java.util.Date getDateTimeValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTimeValue.toString());
	}

	/**
	 * Set value of DateTimeValue
	 * @param datetimevalue
	 */
	public final void setDateTimeValue(java.util.Date datetimevalue)
	{
		setDateTimeValue(getContext(), datetimevalue);
	}

	/**
	 * Set value of DateTimeValue
	 * @param context
	 * @param datetimevalue
	 */
	public final void setDateTimeValue(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetimevalue)
	{
		getMendixObject().setValue(context, MemberNames.DateTimeValue.toString(), datetimevalue);
	}

	/**
	 * @return value of DecimalValue
	 */
	public final java.math.BigDecimal getDecimalValue()
	{
		return getDecimalValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DecimalValue
	 */
	public final java.math.BigDecimal getDecimalValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DecimalValue.toString());
	}

	/**
	 * Set value of DecimalValue
	 * @param decimalvalue
	 */
	public final void setDecimalValue(java.math.BigDecimal decimalvalue)
	{
		setDecimalValue(getContext(), decimalvalue);
	}

	/**
	 * Set value of DecimalValue
	 * @param context
	 * @param decimalvalue
	 */
	public final void setDecimalValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal decimalvalue)
	{
		getMendixObject().setValue(context, MemberNames.DecimalValue.toString(), decimalvalue);
	}

	/**
	 * @return value of IntegerValue
	 */
	public final java.lang.Integer getIntegerValue()
	{
		return getIntegerValue(getContext());
	}

	/**
	 * @param context
	 * @return value of IntegerValue
	 */
	public final java.lang.Integer getIntegerValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.IntegerValue.toString());
	}

	/**
	 * Set value of IntegerValue
	 * @param integervalue
	 */
	public final void setIntegerValue(java.lang.Integer integervalue)
	{
		setIntegerValue(getContext(), integervalue);
	}

	/**
	 * Set value of IntegerValue
	 * @param context
	 * @param integervalue
	 */
	public final void setIntegerValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer integervalue)
	{
		getMendixObject().setValue(context, MemberNames.IntegerValue.toString(), integervalue);
	}

	/**
	 * @return value of LongValue
	 */
	public final java.lang.Long getLongValue()
	{
		return getLongValue(getContext());
	}

	/**
	 * @param context
	 * @return value of LongValue
	 */
	public final java.lang.Long getLongValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.LongValue.toString());
	}

	/**
	 * Set value of LongValue
	 * @param longvalue
	 */
	public final void setLongValue(java.lang.Long longvalue)
	{
		setLongValue(getContext(), longvalue);
	}

	/**
	 * Set value of LongValue
	 * @param context
	 * @param longvalue
	 */
	public final void setLongValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long longvalue)
	{
		getMendixObject().setValue(context, MemberNames.LongValue.toString(), longvalue);
	}

	/**
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue()
	{
		return getStringValue(getContext());
	}

	/**
	 * @param context
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StringValue.toString());
	}

	/**
	 * Set value of StringValue
	 * @param stringvalue
	 */
	public final void setStringValue(java.lang.String stringvalue)
	{
		setStringValue(getContext(), stringvalue);
	}

	/**
	 * Set value of StringValue
	 * @param context
	 * @param stringvalue
	 */
	public final void setStringValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stringvalue)
	{
		getMendixObject().setValue(context, MemberNames.StringValue.toString(), stringvalue);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return queryVariableMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aqcommon.proxies.QueryVariable that = (aqcommon.proxies.QueryVariable) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
