// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqcommon.actions;

import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.core.objectmanagement.member.MendixBoolean;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import system.proxies.FileDocument;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CloneFileDocument extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __CloneSource;
	private system.proxies.FileDocument CloneSource;
	private IMendixObject __CloneTarget;
	private system.proxies.FileDocument CloneTarget;

	public CloneFileDocument(IContext context, IMendixObject CloneSource, IMendixObject CloneTarget)
	{
		super(context);
		this.__CloneSource = CloneSource;
		this.__CloneTarget = CloneTarget;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.CloneSource = this.__CloneSource == null ? null : system.proxies.FileDocument.initialize(getContext(), __CloneSource);

		this.CloneTarget = this.__CloneTarget == null ? null : system.proxies.FileDocument.initialize(getContext(), __CloneTarget);

		// BEGIN USER CODE
		if (__CloneSource == null || __CloneTarget == null) {
			throw new Exception("At least one of the provided FileDocument objects is null");
		}

		if (!CloneSource.getHasContents()) {
			return false;
		}

		try (InputStream inputStream = Core.getFileDocumentContent(getContext(), __CloneSource)) {
			Core.storeFileDocumentContent(getContext(), __CloneTarget, CloneSource.getName(), inputStream);
		}

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CloneFileDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
