// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqcommon.actions;

import java.math.BigDecimal;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.core.CoreRuntimeException;
import com.mendix.datastorage.XPathQuery;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.webui.CustomJavaAction;
import aqcommon.proxies.QueryVariable;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ExecuteXPathQuery extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String Entity;
	private java.lang.String XPathString;
	private java.util.List<IMendixObject> __VariableList;
	private java.util.List<aqcommon.proxies.QueryVariable> VariableList;
	private java.lang.Long Amount;
	private java.lang.Long Offset;

	public ExecuteXPathQuery(IContext context, java.lang.String Entity, java.lang.String XPathString, java.util.List<IMendixObject> VariableList, java.lang.Long Amount, java.lang.Long Offset)
	{
		super(context);
		this.Entity = Entity;
		this.XPathString = XPathString;
		this.__VariableList = VariableList;
		this.Amount = Amount;
		this.Offset = Offset;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.VariableList = java.util.Optional.ofNullable(this.__VariableList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(__VariableListElement -> aqcommon.proxies.QueryVariable.initialize(getContext(), __VariableListElement))
			.collect(java.util.stream.Collectors.toList());

		// BEGIN USER CODE
		List<IMendixObject> results = null;
		
		try {
			java.lang.String xpath = "//" + this.Entity.toString() + (this.XPathString == null ? "" : this.XPathString);
			_logger.debug("xpath :: " + xpath);
			
			XPathQuery xpathQuery = Core.createXPathQuery(xpath);
			xpathQuery.setDepth(1);

			for(QueryVariable variable : VariableList) {
				String variableName = variable.getVariableName().replace("$", "");
				_logger.debug("variableName :: " + variableName);
				switch(variable.getVariableType()) {
					case StringType:
						String stringValue = variable.getStringValue();
						_logger.debug("String value :: " + stringValue);
						xpathQuery.setVariable(variableName, stringValue);
						break;
					case BooleanType:
						Boolean booleanValue = variable.getBooleanValue();
						_logger.debug("Boolean value :: " + booleanValue);
						xpathQuery.setVariable(variableName, booleanValue);
						break;
					case DateTimeType:
						Long dateTimeValue = variable.getDateTimeValue().getTime();
						_logger.debug("DateTime value :: " + dateTimeValue);
						xpathQuery.setVariable(variableName, dateTimeValue);
						break;
					case Decimal:
						BigDecimal decimalValue = variable.getDecimalValue();
						_logger.debug("Decimal value :: " + decimalValue);
						xpathQuery.setVariable(variableName, decimalValue);
						break;
					case IntegerType:
						Integer integerValue = variable.getIntegerValue();
						_logger.debug("Integer value :: " + integerValue);
						xpathQuery.setVariable(variableName, integerValue);
						break;
					case LongType:
						Long longValue = variable.getLongValue();
						_logger.debug("Long value :: " + longValue);
						xpathQuery.setVariable(variableName, longValue);
						break;
					case AssociatedObjectType:
						String associatedObjectValue = variable.getAssociatedObjectValue();
						_logger.debug("Associated Object value :: " + associatedObjectValue);						
						IMendixIdentifier associatedObject =  (IMendixIdentifier)variable.getMendixObject().getValue(getContext(), associatedObjectValue);
						xpathQuery.setVariable(variableName, associatedObject);
						break;
					default:
						_logger.debug("No variable type specified.");
						break;
				}				
			}
			
			if(Amount != null) {
				Integer amount = Amount.intValue();
				_logger.debug("Amount param :: " + amount);
				xpathQuery.setAmount(amount);
			}
			
			if(Offset != null) {
				Integer offset = Offset.intValue();
				_logger.debug("Offset param :: " + offset);
				xpathQuery.setOffset(offset);
			}
						
			results = xpathQuery.execute(getContext());
		}
		catch(CoreRuntimeException err) {
			_logger.error("XPath '" + this.XPathString + "' seems to be invalid");
			throw err;
		}
		
		return results;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteXPathQuery";
	}

	// BEGIN EXTRA CODE
	private final ILogNode _logger = Core.getLogger("ExecuteXPathQuery");
	// END EXTRA CODE
}
