// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqcommon.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetListItemByIndex extends CustomJavaAction<IMendixObject>
{
	private java.util.List<IMendixObject> ListToExtractItemFrom;
	private java.lang.Long ItemIndex;

	public GetListItemByIndex(IContext context, java.util.List<IMendixObject> ListToExtractItemFrom, java.lang.Long ItemIndex)
	{
		super(context);
		this.ListToExtractItemFrom = ListToExtractItemFrom;
		this.ItemIndex = ItemIndex;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		if( ListToExtractItemFrom == null || ItemIndex >= ListToExtractItemFrom.size())
			return null;
		
		return ListToExtractItemFrom.get(ItemIndex.intValue());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetListItemByIndex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
