// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqcommon.actions;

import java.security.PublicKey;
import java.security.Signature;
import java.util.Base64;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import aqcommon.CertificateHelper;

/**
 * Verifies that a string (signed using the SHA1withRSA algorithm) against a public key from a cer file (must be an X509 certificate)
 * 
 * CerFileName : The name of the file stored in resources folder, e.g. 'MyCerFile.cer'. Can also be a path from the resources folder, e.g. 'certs\\MyCerFile.cer'
 * OriginalString: The string that you wish to verify a signed string against.
 * SignedString: The base64 encoded representation of the signed string.
 * 
 * Returns a boolean, indicating whether the string has been verified, or not.
 */
public class VerifySignedStringWithPublicKey extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String CerFileName;
	private java.lang.String OriginalString;
	private java.lang.String SignedString;

	public VerifySignedStringWithPublicKey(IContext context, java.lang.String CerFileName, java.lang.String OriginalString, java.lang.String SignedString)
	{
		super(context);
		this.CerFileName = CerFileName;
		this.OriginalString = OriginalString;
		this.SignedString = SignedString;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if(this.CerFileName == null || this.CerFileName.equalsIgnoreCase(""))
			throw new IllegalArgumentException("CerFileName cannot be empty.");
						
		PublicKey pk = CertificateHelper.GetPublicKeyFromCerFile(this.CerFileName);
		
		Signature sig = Signature.getInstance("SHA1withRSA");
		sig.initVerify(pk);
		sig.update(this.OriginalString.getBytes());
		return sig.verify(Base64.getDecoder().decode(this.SignedString));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "VerifySignedStringWithPublicKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
