// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the TestModule module
	public static void aCT_Note_Save(IContext context, testmodule.proxies.Note _note)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Note", _note == null ? null : _note.getMendixObject());
		Core.microflowCall("TestModule.ACT_Note_Save").withParams(params).execute(context);
	}
	public static void aCT_Notes_DeleteAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TestModule.ACT_Notes_DeleteAll").withParams(params).execute(context);
	}
	public static testmodule.proxies.Note dS_Note_CreateTest(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TestModule.DS_Note_CreateTest").withParams(params).execute(context);
		return result == null ? null : testmodule.proxies.Note.initialize(context, result);
	}
	public static void oCH_Test(IContext context, testmodule.proxies.Note _note)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Note", _note == null ? null : _note.getMendixObject());
		Core.microflowCall("TestModule.OCH_Test").withParams(params).execute(context);
	}
	public static boolean vAL_Note(IContext context, testmodule.proxies.Note _note)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Note", _note == null ? null : _note.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("TestModule.VAL_Note").withParams(params).execute(context);
	}
}
