// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aqcommon.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the AqCommon module

	public static java.lang.String getDuplicateRecordMessage()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AqCommon.DuplicateRecordMessage");
	}

	public static java.lang.String getEnvironmentUrl_Prod()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AqCommon.EnvironmentUrl_Prod");
	}

	public static java.lang.String getEnvironmentUrl_Test()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AqCommon.EnvironmentUrl_Test");
	}

	public static java.lang.String getEnvironmentUrl_UAT()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AqCommon.EnvironmentUrl_UAT");
	}

	public static java.lang.String getRequiredFieldMessage()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AqCommon.RequiredFieldMessage");
	}
}